name: Spellcheck

on:
  - push
  - pull_request

jobs:
  spellcheck:
    name: Spellcheck (documentation)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Aspell
        run: |
          sudo apt-get install aspell aspell-en

      - name: Install the doc framework
        working-directory: ./doc
        run: |
          make install

      - name: Build docs and run spellchecker
        working-directory: ./doc
        run: |
          make spellcheck
